//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class counters
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<int> chnannel { get; set; }
        public Nullable<int> objects_place_id { get; set; }
        public Nullable<int> owner_id { get; set; }
        public Nullable<System.DateTime> date_act { get; set; }
        public Nullable<double> value_act { get; set; }
        public Nullable<int> net_id { get; set; }
        public string serial_amspi { get; set; }
        public string serial_r1 { get; set; }
        public string serial_r2 { get; set; }
        public Nullable<System.DateTime> date_calibration_r1 { get; set; }
        public Nullable<System.DateTime> date_calibration_r2 { get; set; }
        public Nullable<System.DateTime> date_init_calibration_r2 { get; set; }
        public Nullable<System.DateTime> date_init_calibration_r1 { get; set; }
        public Nullable<System.DateTime> date_calibration_amspi { get; set; }
        public Nullable<int> diameter_r1 { get; set; }
        public Nullable<int> diameter_r2 { get; set; }
    }
}
