//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class net
    {
        public net()
        {
            this.objects_place = new HashSet<objects_place>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string commnet { get; set; }
    
        public virtual ICollection<objects_place> objects_place { get; set; }
    }
}
