//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects_place
    {
        public int id { get; set; }
        public Nullable<int> object_type_id { get; set; }
        public Nullable<int> objects_place_id { get; set; }
        public Nullable<int> net_id { get; set; }
        public string name { get; set; }
        public string kod_BTI { get; set; }
        public string flat_id { get; set; }
        public string comment { get; set; }
    
        public virtual net net { get; set; }
    }
}
