//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class options
    {
        public int Id { get; set; }
        public string ip_addr { get; set; }
        public Nullable<int> ip_port { get; set; }
        public string pop_addr { get; set; }
        public Nullable<int> pop_port { get; set; }
        public string pop_mail { get; set; }
        public string pop_passwd { get; set; }
        public string ppu_mail { get; set; }
        public bool pop_ssl { get; set; }
        public Nullable<int> pop_int { get; set; }
        public bool is_mail { get; set; }
        public bool is_ip { get; set; }
        public bool new_ip { get; set; }
        public string new_ip_addr { get; set; }
    }
}
