//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_iz
    {
        public int Id { get; set; }
        public string pt { get; set; }
        public string na { get; set; }
        public int r1 { get; set; }
        public int r1_0 { get; set; }
        public int r1_1 { get; set; }
        public int r1_2 { get; set; }
        public int r1_3 { get; set; }
        public int r1_4 { get; set; }
        public int r1_5 { get; set; }
        public int r1_6 { get; set; }
        public int r1_7 { get; set; }
        public int r1_8 { get; set; }
        public int r1_9 { get; set; }
        public int r1_10 { get; set; }
        public int r1_11 { get; set; }
        public int r1_12 { get; set; }
        public int r1_13 { get; set; }
        public int r1_14 { get; set; }
        public int r1_15 { get; set; }
        public int r1_16 { get; set; }
        public int r1_17 { get; set; }
        public int r1_18 { get; set; }
        public int r1_19 { get; set; }
        public int r1_20 { get; set; }
        public int r1_21 { get; set; }
        public int r1_22 { get; set; }
        public int r1_23 { get; set; }
        public int r1_24 { get; set; }
        public int r2 { get; set; }
        public int r2_0 { get; set; }
        public int r2_1 { get; set; }
        public int r2_2 { get; set; }
        public int r2_3 { get; set; }
        public int r2_4 { get; set; }
        public int r2_5 { get; set; }
        public int r2_6 { get; set; }
        public int r2_7 { get; set; }
        public int r2_8 { get; set; }
        public int r2_9 { get; set; }
        public int r2_10 { get; set; }
        public int r2_11 { get; set; }
        public int r2_12 { get; set; }
        public int r2_13 { get; set; }
        public int r2_14 { get; set; }
        public int r2_15 { get; set; }
        public int r2_16 { get; set; }
        public int r2_17 { get; set; }
        public int r2_18 { get; set; }
        public int r2_19 { get; set; }
        public int r2_20 { get; set; }
        public int r2_21 { get; set; }
        public int r2_22 { get; set; }
        public int r2_23 { get; set; }
        public int r2_24 { get; set; }
        public int pw1 { get; set; }
        public int pw2 { get; set; }
        public int gp { get; set; }
        public string te { get; set; }
        public int vc { get; set; }
        public int vg { get; set; }
        public int ti { get; set; }
        public string sn1 { get; set; }
        public string sn2 { get; set; }
        public System.DateTime da { get; set; }
        public System.DateTime date_inc { get; set; }
        public string mail_uid { get; set; }
        public Nullable<bool> ismail { get; set; }
    }
}
