//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_al
    {
        public int Id { get; set; }
        public string pt { get; set; }
        public string na { get; set; }
        public int wr { get; set; }
        public Nullable<System.DateTime> date_inc { get; set; }
        public Nullable<bool> ismail { get; set; }
        public string mail_uid { get; set; }
        public string wr_txt { get; set; }
    }
}
