//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_on
    {
        public int Id { get; set; }
        public string pt { get; set; }
        public string na { get; set; }
        public int r1 { get; set; }
        public int r2 { get; set; }
        public int pw1 { get; set; }
        public int pw2 { get; set; }
        public int gp { get; set; }
        public int te { get; set; }
        public int vc { get; set; }
        public int vg { get; set; }
        public Nullable<int> ti { get; set; }
        public string sn1 { get; set; }
        public string sn2 { get; set; }
        public System.DateTime da { get; set; }
        public System.DateTime date_time_inc { get; set; }
        public string mail_uid { get; set; }
        public Nullable<bool> ismail { get; set; }
    }
}
