//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodopriborUchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class warning_conditions
    {
        public int Id { get; set; }
        public Nullable<double> gprs_sig_min { get; set; }
        public Nullable<double> gprs_sig_max { get; set; }
        public Nullable<double> gprs_mod_min { get; set; }
        public Nullable<double> gprs_mod_max { get; set; }
        public Nullable<double> controller_voltage_min { get; set; }
        public Nullable<double> controller_voltage_max { get; set; }
    }
}
